---
services:
  unbound:
    build:
      context: .
      args:
        UNBOUND_VERSION: ${UNBOUND_VERSION}
        UNBOUND_SRC_SHA256: ${UNBOUND_SRC_SHA256}
        IMAGE_REVISION: ${IMAGE_REVISION}
        BASE_IMAGE: ${BASE_IMAGE}
        TZ: ${TZ}
      tags:
        - "ghcr.io/carme-264pp/${UNBOUND_TAG_NAME}:latest"
        - "ghcr.io/carme-264pp/${UNBOUND_TAG_NAME}:v${UNBOUND_VERSION}-${IMAGE_REVISION}"
    image: ghcr.io/carme-264pp/${UNBOUND_TAG_NAME}:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./conf:/etc/unbound:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
