---
services:
  unbound:
    build:
      context: .
      tags:
        - "unbound-docker:latest"
        - "unbound-docker:v1.23.0"
    image: ghcr.io/carme-264pp/unbound-docker:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./conf:/etc/unbound:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
